name: Bump cua-agent Version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    uses: ./.github/workflows/bump-version-reusable.yml
    with:
      package_name: "cua-agent"
      package_directory: "libs/python/agent"
      bump_type: ${{ inputs.bump_type }}
    secrets: inherit
