name: Bump cua-computer Version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    uses: ./.github/workflows/bump-version-reusable.yml
    with:
      package_name: 'cua-computer'
      package_directory: 'libs/python/computer'
      bump_type: ${{ inputs.bump_type }}
    secrets: inherit
